title: "Carlos A. Benavides-Gallego"
author: "Carlos Benavidesg"
description: "Olympia Academy"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true            # adds a gray frame to the site
show_sidebar: true          # show a sidebar instead of the usual header
minimal: false              # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "home.md", title: "Home"}
  - {file: "index.html", title: "News"}
  #- {file: "CV.pdf", title: "CV"}
  #- {file:"about_me.md", title: "About me"}
  #- {file: "README.md",title: "About me"}
  #- {title: "Research"}
  #- {file: "news.md", title: "News"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:cabenavidesg@unal.edu.co"}
  - {title: Github, icon: github, url: "https://github.com/cabenavidesg"}
  - {title: Inspire.net, icon: rss, url: "https://inspirehep.net/authors/1721044?ui-citation-summary=true&ui-exclude-self-citations=true"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
